stages:
  data_ingestion:
    cmd: python src/Kidney_Disease_Classification/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Kidney_Disease_Classification/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion


  prepare_base_model:
    cmd: python src/Kidney_Disease_Classification/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/Kidney_Disease_Classification/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - image_size
      - learning_rate
      - include_top
      - weights
      - classes
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/Kidney_Disease_Classification/pipeline/stage_03_model_training.py
    deps:
      - src/Kidney_Disease_Classification/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion
    params:
      - image_size
      - batch_size
      - epochs
      - augmentation
    outs:
      - prediction_model/updated_model.h5
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/Kidney_Disease_Classification/pipeline/stage_04_model_evaluation.py
    deps:
      - src/Kidney_Disease_Classification/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion
      - artifacts/training/model.h5
    params:
      - image_size
      - batch_size
    metrics:
    - scores.json:
        cache: false