artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts
  base_model_path: artifacts/training/model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_model.h5



training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5


evaluation:
  path_of_model: artifacts/model.h5
  training_data: artifacts/data_ingestion
  mlflow_uri: https://dagshub.com/chirag003214/Kidney-Disease-Classification.mlflow
